package rubiconproject.hash;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import rubiconproject.FileHash;
import rubiconproject.FileUtil;

import java.io.File;
import java.io.IOException;
import java.util.List;

/**
 * Calculate hash for {@link File} file or directory using {@link HashGenerator} algorithm
 */
public class FileHashUtil {
    private static final Logger LOG = LogManager.getLogger(FileHashUtil.class);
    private static final HashGenerator GENERATOR = new Sha512HashGenerator();

    /**
     * Calculate hash for directory
     * The hash of a directory is generated by hashing each file or subdirectory in alphabetical order,
     * then concatenating the hashed value, then applying SHA-512 hash to the results
     *
     * @param file {@link File} directory
     * @param internalList {@link List} of {@link FileHash} internal files or directories
     * @return {@link String} hash result
     */
    public static String dirHash(File file, List<FileHash> internalList) {
        StringBuilder builder = new StringBuilder();
        for (FileHash fh : internalList) {
            builder.append(fh.getHash());
        }
        String hash = GENERATOR.getHash(builder.toString().getBytes());
        LOG.info("Dir {} hash is {}", file.getName(), hash);
        return hash;
    }

    /**
     * Calculate hash for file
     * The hash of a file is a hash of its contents then hexed encoded.
     *
     * @param file {@link File} file
     * @return {@link FileHash} result
     */
    public static FileHash fileHash(File file) {
        byte[] content = FileUtil.readFile(file);
        String hash = GENERATOR.getHash(content);
        LOG.info("File {} hash is {}", file.getName(), hash);

        return FileHash.builder()
                .setFileName(file.getName())
                .setHash(hash)
                .build();
    }
}
